baseURL = "https://blog.mohalfan.my.id/"
title = "Alfan Mohammad"
languageCode = "id-ID"
defaultContentLanguage = "id"
theme = "Bareblog"
enableRobotsTXT = true

[taxonomies]
  tag = "tags"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    name = "Now"
    url = "/now"
    weight = 15

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20

  [[menu.main]]
    name = "Guestbook"
    url = "/guestbook/"
    weight = 30

[params]
  description = "Blog personal tentang desain dan teknologi."
  
  # Pastikan tidak ada karakter aneh sebelum [params.author]
  [params.author] 
    name = "Alfan Mohammad"
    email = "muhalfan1505@gmail.com"

  keywords = ["desain", "ilustrasi", "web development", "freelancer"]
  google_analytics = "G-0G9SMH8JWB"

  [params.footer]
    hideRSSAndEmail = false
    hideSitemap = false

  [params.rss]
    enableRSS = true

  [params.opengraph]
    site_name = "Alfan Mohammad"
    type = "website"
    image = "/images/og-image.jpg"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
