# URL utama blog yang digunakan Hugo untuk menghasilkan link absolut
baseURL = "https://yourdomain.com"

# Judul situs yang akan tampil di <title> dan metadata
title = "My Personal Blog"

# Kode bahasa utama situs
languageCode = "id-ID"

# Bahasa konten default
defaultContentLanguage = "id"

# Nama tema yang digunakan (pastikan folder tema sudah ada)
theme = "Bareblog"

# Aktifkan agar Hugo menghasilkan file robots.txt secara otomatis
enableRobotsTXT = true

# Informasi penulis situs
[author]
  email = "emailkamu@gmail.com"  # Email penulis

# Taksonomi: definisi kategori/tag yang digunakan untuk mengelompokkan konten
[taxonomies]
  tag = "tags"  # Tag digunakan untuk menandai konten

# Navigasi menu utama
[menu]

  [[menu.main]]
    identifier = "home"        # ID unik untuk menu ini
    name = "Home"              # Nama yang muncul di menu
    url = "/"                  # Tautan tujuan
    weight = 1                 # Urutan menu (semakin kecil, semakin atas)

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    name = "Now"
    url = "/now"
    weight = 15

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20

  [[menu.main]]
    name = "Guestbook"
    url = "/guestbook/"
    weight = 30

# Parameter kustom untuk tema atau SEO
[params]
  description = "Blog personal tentang keseharian."       # Deskripsi situs (penting untuk SEO)
  author = "Alfan Mohammad"                               # Nama penulis
  keywords = ["desain", "ilustrasi", "web development", "freelancer"]  # Kata kunci SEO
  google_analytics = "G-XXXXXXXXX"                        # ID Google Analytics (GA4)

  [params.footer]
    hideRSSAndEmail = false   # Tampilkan RSS dan email di footer
    hideSitemap = false       # Tampilkan sitemap di footer

  [params.rss]
    enableRSS = true          # Aktifkan RSS feed untuk blog

  [params.opengraph]
    site_name = "Nama Blog"             # Nama untuk Open Graph (saat dibagikan di media sosial)
    type = "website"                    # Tipe konten OG
    image = "/images/og-image.jpg"      # Gambar default untuk share (media sosial, Twitter)

# Konfigurasi sitemap.xml untuk SEO
[sitemap]
  changefreq = "daily"        # Frekuensi perubahan situs
  priority = 0.5              # Prioritas URL (1 = paling penting)
  filename = "sitemap.xml"    # Nama file sitemap yang dihasilkan

# Pengaturan Markdown renderer Goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Izinkan raw HTML dalam Markdown (jika perlu embed kode HTML)